### ISSUE TITLE
buffer does not contain relative step

### ISSUE THREAD

**Issue by mkchungs** [shazow/whatsabi#42]
I'm getting this error:_**buffer does not contain relative step**_ when trying to get selectors for Ethereum contract at [0x37c6e59e1ae39d81828db1a8e8233d6b2afcb9a8](https://etherscan.io/address/0x37c6e59e1ae39d81828db1a8e8233d6b2afcb9a8#code) 

Minimal code to reproduce the problem:
```
const whatsabi = require("@shazow/whatsabi")
let bytecode = '0x5b602960346000f073032be5d2772329c11a72dadb32ce03806bb26f0a3160005760006000600060003031335af15060006000f36000600060206000600073032be5d2772329c11a72dadb32ce03806bb26f0a5a6069600052f15033ff'
let selectors = whatsabi.selectorsFromBytecode(bytecode)
```
Errors:
```
> let selectors = whatsabi.selectorsFromBytecode(bytecode)
Uncaught Error: buffer does not contain relative step
    at BytecodeIter.asPos (/root/go/src/github.com/colorfulnotion/evm-etl/node_modules/@shazow/whatsabi/lib/disasm.js:67:23)
    at BytecodeIter.at (/root/go/src/github.com/colorfulnotion/evm-etl/node_modules/@shazow/whatsabi/lib/disasm.js:76:26)
    at disasm (/root/go/src/github.com/colorfulnotion/evm-etl/node_modules/@shazow/whatsabi/lib/disasm.js:213:44)
    at abiFromBytecode (/root/go/src/github.com/colorfulnotion/evm-etl/node_modules/@shazow/whatsabi/lib/disasm.js:136:15)
    at Object.selectorsFromBytecode (/root/go/src/github.com/colorfulnotion/evm-etl/node_modules/@shazow/whatsabi/lib/selectors.js:22:46)
> 
```
Any helps?

**Comment by shazow** [comment]
Hiya, which version of whatsabi are you using?

**Comment by shazow** [comment]
Cool thanks, I'll look into this soon, thanks for reporting. :)

**Comment by shazow** [comment]
Should be fixed in main. Will do a v0.6.1 release shortly!

**Comment by shazow** [comment]
[v0.6.1](https://github.com/shazow/whatsabi/releases) should be published, let me know if you're still having problems!
